services:
  app:
    image: 'bike-theft-check'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      POSTGRES_URL: $POSTGRES_URL
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_SCHEMA: $POSTGRES_SCHEMA
      TGBOT_PATH: $TGBOT_PATH
      TGBOT_BOTNAME: $TGBOT_BOTNAME
      TGBOT_TOKEN: $TGBOT_TOKEN
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/