spring:
  application:
    name: bike_theft_check
  liquibase:
    change-log: classpath://db/changelog/changelog.xml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      schema: ${POSTGRES_SCHEMA:bike}
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      pool-name: datasource-pool-bike
    initialization-mode: always
  jpa:
    database: postgresql
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
    generate-ddl: false
    open-in-view: off
  task:
    scheduling:
      pool:
        size: 5
cron:
  rss: 0 30 3 * * ?
  parser: 0 0 4 * * ?
telegram:
  botPath: ${TGBOT_PATH:https://4689-88-118-182-80.ngrok-free.app}
  botUsername: ${TGBOT_BOTNAME:BikeTheftCheck}
  botToken: ${TGBOT_TOKEN:6297562865:AAHmoQfoV_d_0u6Om178U5U9ncyOIRM4egk}
rss:
  baseUrl: ${RSS_URL:https://veloby.net/stolen-bikes/rss}