spring:
  application:
    name: bike_theft_check
  liquibase:
    change-log: classpath://db/changelog/changelog.xml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      schema: ${POSTGRES_SCHEMA:bike}
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      pool-name: datasource-pool-bike
    initialization-mode: always
  jpa:
    database: postgresql
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
    generate-ddl: false
    open-in-view: off
  task:
    scheduling:
      pool:
        size: 5
cron:
  parser: 0 0 4 * * ?
telegram:
  botPath: ${TGBOT_PATH:https://1e79-88-118-182-80.ngrok-free.app}
  botUsername: ${TGBOT_BOTNAME:bot}
  botToken: ${TGBOT_TOKEN:token}
rss:
  baseUrl: ${RSS_URL:https://veloby.net/stolen-bikes/rss}