package com.bragin.bike_theft_check.model;

public enum BotState {
    CREATE,
    ENTER_FRAME_NUMBER,
    ENTER_VENDOR,
    ENTER_MODEL_NAME,
    ENTER_DESCRIPTION,
    FIND_BIKE,
    START,
    MY_BIKES,
    ENTER_FRAME_NUMBER_FOR_SEARCH,
    INFO,
    UPDATE_BIKES;
//    ENTER_VENDOR_FOR_UPDATE,
//    ENTER_MODEL_NAME_FOR_UPDATE,
//    ENTER_DESCRIPTION_FOR_UPDATE,
//    ENTER_WANTED,
//    ENTER_FRAME_NUMBER_FOR_UPDATE;
}
